//
//  Localizations.swift
//  MathClass
//
//  FR→EN translation table. Keys are the existing French copy in views.
//  Missing keys fall through to themselves (so a French user sees French
//  even if a translation is missing). When adding new strings to a view
//  in French, also add their English counterpart here.
//
//  For interpolated strings, prefer LocalizationManager.shared.format(_:_:)
//  with %@ placeholders rather than wrapping the whole interpolated string.
//

import Foundation

enum Localizations {
    static let fr2en: [String: String] = [
        // MARK: Added 2026-09 (coverage gaps)
        "Impossible de charger votre profil": "Couldn't load your profile",
        "Vérifiez votre connexion internet puis réessayez. Si le problème persiste, déconnectez-vous et reconnectez-vous.": "Check your internet connection and try again. If the problem persists, sign out and sign back in.",
        "Se déconnecter": "Sign out",
        "Professeur": "Teacher",
        "Gérer les classes, créer et assigner des exercices": "Manage classes, create and assign exercises",
        "Entrer le code classe pour accéder aux exercices": "Enter the class code to access exercises",
        "Taux de réussite de l'élève comparé à la moyenne de la classe par compétence.": "Student success rate compared with the class average, per competency.",
        "La réinitialisation efface uniquement les données de démo, pas vos vraies classes.": "Resetting only erases the demo data, not your real classes.",
        "Données de démo chargées.": "Demo data loaded.",
        "Niveau": "Level",
        "Démo réinitialisée.": "Demo reset.",
        "Élève vs moyenne de la classe": "Student vs class average",
        "Réinitialiser la démo ?": "Reset the demo?",

        // MARK: Common verbs / actions
        "OK": "OK",
        "Annuler": "Cancel",
        "Ajouter": "Add",
        "Sauvegarder": "Save",
        "Enregistrer": "Save",
        "Supprimer": "Delete",
        "Modifier": "Edit",
        "Éditer": "Edit",
        "Fermer": "Close",
        "Retour": "Back",
        "Précédent": "Previous",
        "Suivant": "Next",
        "Réessayer": "Retry",
        "Réinitialiser": "Reset",
        "Sélectionner": "Select",
        "Appliquer": "Apply",
        "Valider": "Submit",
        "Soumettre": "Submit",
        "Vérifier": "Check",
        "Recharger": "Reload",
        "Effacer": "Clear",
        "Refaire": "Redo",
        "Créer": "Create",
        "Rechercher…": "Search…",
        "Se connecter": "Sign in",
        "Déconnexion": "Sign out",
        "Déconnecter": "Sign out",
        "Ne pas sauvegarder": "Don't save",
        "Tous": "All",
        "Toutes": "All",
        "Aucun": "None",
        "ou": "or",
        "—": "—",
        "lié": "linked",

        // MARK: Auth / account
        "Connexion Professeur": "Teacher Sign-In",
        "Inscription Professeur": "Teacher Sign-Up",
        "Connexion Élève": "Student Sign-In",
        "Connexion…": "Signing in…",
        "Supprimer mon compte": "Delete my account",
        "Supprime définitivement votre compte, vos classes, le travail de vos élèves et vos exercices.": "Permanently deletes your account, your classes, your students' work and your exercises.",
        "Supprimer votre compte ?": "Delete your account?",
        "Supprimer définitivement": "Delete permanently",
        "Cette action est irréversible.": "This cannot be undone.",
        "Classe de démo prête.": "Demo class ready.",
        "Données de démo supprimées.": "Demo data deleted.",
        "Créer un compte": "Create an account",
        "Créer le compte": "Create account",
        "MathClass pour Professeurs": "MathClass for Teachers",
        "Mon profil": "My profile",
        "Profil mis à jour": "Profile updated",
        "Email": "Email",
        "Nom": "Last name",
        "Prénom": "First name",
        "Le mot de passe doit contenir :": "Password must contain:",
        "Au moins 6 caractères": "At least 6 characters",
        "Au moins un chiffre": "At least one digit",
        "Au moins une majuscule": "At least one uppercase letter",
        "• Au moins 6 caractères": "• At least 6 characters",
        "• Au moins un chiffre": "• At least one digit",
        "• Au moins une lettre majuscule": "• At least one uppercase letter",
        "Voulez-vous vraiment vous déconnecter ?": "Are you sure you want to sign out?",
        "Êtes-vous sûr de vouloir vous déconnecter ?": "Are you sure you want to sign out?",
        "Bienvenue !": "Welcome!",
        "Sélectionnez votre profil": "Select your profile",
        "Membre depuis": "Member since",
        "Connecté: %@": "Signed in: %@",
        "Connecté : %@": "Signed in: %@",

        // MARK: Class management
        "Classe": "Class",
        "Classes": "Classes",
        "Nouvelle Classe": "New class",
        "Nouvelle classe": "New class",
        "Nom de la classe": "Class name",
        "Code classe": "Class code",
        "Code classe:": "Class code:",
        "Créer la classe": "Create class",
        "Toutes les classes": "All classes",
        "Sélectionnez une classe": "Select a class",
        "Sélectionner une classe": "Select a class",
        "Liste des élèves": "Student list",
        "Aucun élève dans cette classe.": "No students in this class.",
        "Êtes-vous sûr de vouloir supprimer cette classe et tous ses élèves ?": "Are you sure you want to delete this class and all its students?",
        "Supprimer la classe": "Delete class",
        "Modifier la classe": "Edit class",

        // MARK: Students
        "Élève": "Student",
        "Élèves": "Students",
        "Ajouter un élève": "Add student",
        "Ajouter Élève": "Add student",
        "Modifier l'élève": "Edit student",
        "Supprimer l'élève": "Delete student",
        "Êtes-vous sûr de vouloir supprimer cet élève ?": "Are you sure you want to delete this student?",
        "Sélectionnez votre nom": "Select your name",
        "Sélectionnez un élève": "Select a student",
        "Code: %@": "Code: %@",
        "Demandez le code à votre professeur.\nIl ressemble à MX-XXXX.": "Ask your teacher for the code.\nIt looks like MX-XXXX.",
        "Entrez le code de votre classe\npour accéder à vos exercices.": "Enter your class code\nto access your exercises.",
        "MX-XXXX": "MX-XXXX",
        "Un élève par ligne au format « Prénom Nom »": "One student per line, format \"FirstName LastName\"",
        "Collez votre liste : un élève par ligne. Les en-têtes et séparateurs sont détectés automatiquement.": "Paste your list: one student per line. Headers and separators are detected automatically.",
        "Collez votre liste. Détection automatique : tabulations, points-virgules, virgules ou espaces. Les en-têtes français (nom, prénom) sont reconnus.": "Paste your list. Auto-detected: tabs, semicolons, commas, or spaces. French headers (nom, prénom) are recognized.",
        "Choisir un fichier CSV...": "Choose a CSV file…",
        "Sélectionner un fichier": "Choose a file",
        "Classement des élèves": "Student ranking",

        // MARK: Exercises
        "Exercice": "Exercise",
        "Exercices": "Exercises",
        "Ajouter un exercice": "Add exercise",
        "Ajouter Exercice": "Add exercise",
        "Modifier l'exercice": "Edit exercise",
        "Supprimer l'exercice": "Delete exercise",
        "Êtes-vous sûr de vouloir supprimer cet exercice ?": "Are you sure you want to delete this exercise?",
        "Aucun exercice": "No exercises",
        "Aucun exercice créé.": "No exercises created.",
        "Aucun exercice assigné.": "No exercises assigned.",
        "Ajoutez des exercices depuis la liste de gauche": "Add exercises from the list on the left",
        "Chargement des exercices…": "Loading exercises…",
        "Exercice introuvable": "Exercise not found",
        "Sélectionnez un exercice pour voir les détails": "Select an exercise to see details",
        "Sélectionnez un exercice pour voir l'analyse des erreurs": "Select an exercise to see error analysis",
        "Titre": "Title",
        "Titre de l'exercice": "Exercise title",
        "Entrez le titre": "Enter the title",
        "Énoncé": "Statement",
        "Énoncé — LaTeX": "Statement — LaTeX",
        "Énoncé extrait (modifiable)": "Extracted statement (editable)",
        "L'énoncé extrait apparaîtra ici après l'extraction…": "The extracted statement will appear here after extraction…",
        "Réponse attendue": "Expected answer",
        "Difficulté": "Difficulty",
        "Niveau %d": "Level %d",
        "Aperçu": "Preview",
        "Aperçu:": "Preview:",
        "Afficher l'aperçu": "Show preview",
        "L'aperçu apparaîtra ici…": "The preview will appear here…",
        "ex: x = 5": "ex: x = 5",
        "ex: x = -3 \\text{ ou } x = 0": "ex: x = -3 \\text{ or } x = 0",
        "Mode": "Mode",
        "WYSIWYG": "WYSIWYG",
        "LaTeX": "LaTeX",
        "Importer depuis une photo": "Import from a photo",
        "Photographiez ou choisissez une image de l'énoncé pour pré-remplir automatiquement le titre, l'énoncé et la réponse attendue.": "Photograph or pick an image of the statement to auto-fill the title, statement, and expected answer.",
        "Choisir une photo": "Choose a photo",
        "Glissez une image ici": "Drop an image here",
        "Image source": "Source image",
        "Image de l'exercice": "Exercise image",
        "Image indisponible": "Image unavailable",
        "Changer l'image": "Change image",
        "Import image": "Image import",
        "Extraire avec l'IA": "Extract with AI",
        "Extraction en cours…": "Extracting…",
        "Extraction…": "Extracting…",

        // MARK: Chapters / Competencies
        "Chapitre": "Chapter",
        "Nouveau chapitre": "New chapter",
        "Nom du chapitre": "Chapter name",
        "Aucun chapitre. Ajoutez des chapitres pour organiser les exercices.": "No chapters. Add chapters to organize exercises.",
        "Compétence": "Competency",
        "Compétences": "Competencies",
        "Par compétence": "By competency",
        "Compétences les plus faibles": "Weakest competencies",
        "Aucune compétence dans ce chapitre.": "No competencies in this chapter.",
        "Aucune donnée de compétence disponible.": "No competency data available.",
        "Libellé de la compétence": "Competency label",

        // MARK: Assignments
        "Devoirs": "Assignments",
        "Devoirs actifs": "Active assignments",
        "Aucun devoir": "No assignments",
        "Aucun devoir actif": "No active assignments",
        "Nouveau devoir": "New assignment",
        "Créer un devoir": "Create an assignment",
        "Créer le devoir": "Create assignment",
        "Détail du devoir": "Assignment detail",
        "Sélectionnez un devoir pour voir les détails": "Select an assignment to see details",
        "Créez un devoir pour assigner des exercices à vos élèves.": "Create an assignment to give exercises to your students.",
        "Vérifier les nouveaux devoirs": "Check for new assignments",
        "Votre professeur n'a pas encore\nassigné de devoir à votre classe.": "Your teacher hasn't assigned\nany work to your class yet.",
        "Vous avez terminé tous les exercices\nde ce devoir.": "You've finished every exercise\nin this assignment.",
        "Êtes-vous sûr de vouloir supprimer ce devoir ?": "Are you sure you want to delete this assignment?",
        "Êtes-vous sûr de vouloir supprimer ce devoir et tous ses exercices associés ?": "Are you sure you want to delete this assignment and all of its exercises?",
        "Supprimer le devoir": "Delete assignment",
        "Cibler des élèves": "Target students",
        "Sélectionnez les élèves (vide = tous) :": "Select students (empty = everyone):",
        "Nom du groupe (optionnel)": "Group name (optional)",
        "Exercices disponibles": "Available exercises",
        "Exercices sélectionnés": "Selected exercises",

        // MARK: Submissions
        "Soumissions": "Submissions",
        "Soumissions récentes": "Recent submissions",
        "Aucune soumission": "No submissions",
        "Sélectionnez une soumission": "Select a submission",
        "Les soumissions des élèves apparaîtront ici dès qu'elles seront envoyées.": "Student submissions will appear here as soon as they are sent.",
        "Les travaux soumis par vos élèves apparaîtront ici en temps réel.": "Work submitted by your students will appear here in real time.",
        "Aucun PNG enregistré pour cette soumission.": "No PNG saved for this submission.",
        "Soumission en cours…": "Submitting…",
        "Soumission enregistrée": "Submission recorded",
        "Votre travail a été envoyé.\nVotre professeur verra les résultats.": "Your work has been sent.\nYour teacher will see the results.",
        "Votre travail est en cours de vérification.": "Your work is being checked.",
        "Analyse de votre travail en cours.": "Analyzing your work…",
        "Correction en cours…": "Grading…",
        "En attente": "Pending",
        "En attente de correction": "Awaiting grading",
        "Essai %d": "Attempt %d",

        // MARK: Modes
        "Chaque élève/groupe reçoit des exercices ciblés.": "Each student/group gets targeted exercises.",
        "Progression automatique par niveau de difficulté.": "Automatic progression by difficulty level.",
        "Mode contrôle : aucun feedback pour l'élève.": "Test mode: no feedback for the student.",
        "L'élève voit quelle étape est fausse.": "The student sees which step is wrong.",
        "Le professeur voit les résultats.": "The teacher sees the results.",
        "2e chance possible.": "Second chance allowed.",
        "2e chance possible (remet le compteur à zéro).": "Second chance allowed (resets the counter).",
        "2e chance": "Second chance",
        "Un seul essai.": "One attempt only.",
        "3 réussites consécutives = niveau suivant.": "3 in a row = next level.",
        "Niveau actuel :": "Current level:",
        "Niveau supérieur !": "Level up!",
        "Réussites consécutives :": "Consecutive successes:",
        "Vous passez au niveau %d.": "You're moving up to level %d.",

        // MARK: Feedback
        "Feedback": "Feedback",
        "Bravo !": "Well done!",
        "Excellent ! Réponse correcte du premier coup.": "Excellent! Correct on the first try.",
        "Bien joué ! Réponse correcte au deuxième essai.": "Nice work! Correct on the second try.",
        "La réponse n'est pas correcte.\nRevisez cette notion pour progresser.": "The answer isn't correct.\nReview this concept to make progress.",
        "Aucune erreur détectée dans les étapes.": "No errors detected in the steps.",
        "Détail par étape": "Step-by-step detail",
        "Étape %d": "Step %d",
        "← Première erreur": "← First error",
        "← Première erreur ici": "← First error here",
        "Étapes reconnues": "Recognized steps",
        "Aucune étape reconnue": "No step recognized",
        "Aucune étape reconnue.": "No step recognized.",
        "La reconnaissance n'a rien lu sur votre dessin.\nRetournez au dessin pour réécrire plus lisiblement, ou réessayez la reconnaissance.": "The recognizer couldn't read your drawing.\nGo back and rewrite more legibly, or retry recognition.",
        "Reconnaissance de l'écriture…": "Recognizing handwriting…",
        "Reconnaître à nouveau": "Recognize again",
        "Retour au dessin": "Back to drawing",
        "Vérifiez que ces étapes correspondent à votre travail. Modifiez si besoin.": "Check these steps match your work. Edit if needed.",

        // MARK: Statistics
        "Statistiques": "Statistics",
        "Statut": "Status",
        "Résultat": "Result",
        "Vue d'ensemble": "Overview",
        "Vue d'ensemble — %@": "Overview — %@",
        "Analyse des erreurs par étape": "Per-step error analysis",
        "Expressions erronées les plus fréquentes :": "Most frequent erroneous expressions:",
        "Les étapes les plus problématiques sont mises en évidence.": "The most problematic steps are highlighted.",
        "Erreur détaillée": "Detailed error",
        "Aucune erreur détectée": "No errors detected",
        "Élèves en difficulté": "Students struggling",
        "Aucun élève en difficulté !": "No struggling students!",
        "(< 40% de réussite)": "(< 40% success rate)",
        "Aucune donnée": "No data",
        "Les statistiques apparaîtront lorsque des élèves auront soumis des travaux.": "Statistics will appear once students have submitted work.",
        "Progression": "Progress",
        "Travail manuscrit": "Handwritten work",
        "Votre travail": "Your work",
        "Vérification": "Verification",

        // MARK: Misc / errors
        "Erreur": "Error",
        "Erreur de sauvegarde": "Save error",
        "Sauvegarde en cours…": "Saving…",
        "Modifications non sauvegardées": "Unsaved changes",
        "Voulez-vous sauvegarder les modifications avant de fermer ?": "Save changes before closing?",
        "Sélectionnez une section": "Select a section",

        // MARK: Additional UI labels (auto-detected gaps)
        "Actifs": "Active",
        "Compte": "Account",
        "Confirmer le mot de passe": "Confirm password",
        "Connexion": "Sign in",
        "Créé le": "Created on",
        "Groupe": "Group",
        "Informations": "Information",
        "Informations de l'élève": "Student information",
        "Informations de la classe": "Class information",
        "Informations personnelles": "Personal information",
        "Mode de création": "Creation method",
        "Mode du devoir": "Assignment mode",
        "Mot de passe": "Password",
        "Méthode d'import": "Import method",
        "Réponse attendue (LaTeX)": "Expected answer (LaTeX)",
        "Résumé": "Summary",
        "Terminés": "Done",
        "Vue": "View",
        "Élèves (vide = tous)": "Students (empty = everyone)",
        "Élèves en difficulté (< 40%)": "Struggling students (< 40%)",
        "Énoncé (LaTeX et texte)": "Statement (LaTeX and text)",

        // MARK: Language picker
        "Langue": "Language",
        "Préférence linguistique": "Language preference",
        "Choisissez la langue de l'application. Le changement est immédiat.": "Choose the app language. The change is immediate.",
        "Chargement...": "Loading…",
        "Chargement…": "Loading…",
        "Niveau initial (1–5)": "Initial level (1–5)",
        "Le niveau guide la différenciation : exercices et progression sont adaptés au niveau initial.": "The level drives differentiation: exercises and progression adapt to the starting level.",
        "Coller": "Paste",
        "Manuel": "Manual",
        "Fichier CSV": "CSV file",
        "Importer un CSV": "Import a CSV",
        "Aucun fichier importé": "No file imported",
        "Échec du fichier : %@": "File failed: %@",
        "Groupes": "Groups",
        "Ajouter un groupe": "Add a group",
        "Modifier le groupe": "Edit group",
        "Supprimer le groupe": "Delete group",
        "Êtes-vous sûr de vouloir supprimer ce groupe ?": "Are you sure you want to delete this group?",
        "Aucun groupe": "No groups",
        "Glissez les élèves vers un groupe pour les organiser.": "Drag students to a group to organize them.",
        "Membres": "Members",
        "Sans groupe": "No group",
        "Compétences suggérées": "Suggested competencies",
        "L'IA propose ces compétences. Décochez celles qui ne correspondent pas.": "The AI suggests these competencies. Uncheck the ones that don't fit.",
        "Note de notation": "Notation note",
        // Notation-note phrases — keys come from the Cloud Function's fixed
        // taxonomy (NOTATION_KEYS in correct_submission.py), localized by
        // NotationNote.localizedMessage(forKey:) in Submission.swift.
        "Pensez à mettre les négatifs entre parenthèses, par exemple (-3) plutôt que -3.":
            "Wrap negatives in parentheses — e.g. (-3) rather than -3.",
        "Choisissez la virgule ou le point pour les décimaux et restez cohérent.":
            "Pick either the comma or the period for decimals and stick to it.",
        "Notez explicitement la multiplication, par exemple 2·x au lieu de 2x.":
            "Write multiplication explicitly — e.g. 2·x rather than 2x.",
        "Pensez à indiquer l'unité dans la réponse.":
            "Remember to include the unit in the answer.",
        "Mettez les parenthèses autour des fractions ambiguës (par exemple (1/2)x).":
            "Wrap ambiguous fractions in parentheses — e.g. (1/2)x.",
        "Utilisez x^2 plutôt que xx pour les puissances.":
            "Use x^2 rather than xx for powers.",
        "Notation stricte": "Strict notation",
        "L'IA signale les problèmes de notation séparément, sans pénaliser le fond.": "The AI flags notation problems separately, without penalizing the math.",
        "Réglages de la classe": "Class settings",
        "Scanner un QR code": "Scan a QR code",
        "Vue d'ensemble en direct": "Live overview",
        "Aucune séance active": "No active session",
        "Aucun élève inscrit": "No students enrolled",
        "Pas encore commencé": "Not started yet",
        "En cours": "In progress",
        "Terminé": "Done",
        "Plus": "More",
        "En direct": "Live",
        "Tendances": "Trends",
        "Progression par compétence (12 semaines)": "Per-concept progress (12 weeks)",
        "Taux de réussite par compétence, semaine par semaine.": "Success rate per competency, week by week.",
        "Types d'erreurs (IA)": "Error types (AI)",
        "Catégorisation automatique des étapes erronées par l'IA.": "Automatic categorization of failed steps by the AI.",
        "Erreurs liées (X → Y)": "Linked errors (X → Y)",
        "Carte des erreurs (X → Y)": "Error map (X → Y)",
        "Lecture : si l'élève commet X, quelle est la probabilité qu'il commette aussi Y ?":
            "Read as: if a student makes X, how likely are they to also make Y?",
        "Les élèves qui font l'erreur X font aussi souvent l'erreur Y.": "Students who make error X often also make error Y.",
        "Comparaison à la moyenne de classe": "vs. class average",
        "Exporter en PDF": "Export to PDF",
        "Rapport - %@": "Report - %@",
        "PDF exporté": "PDF exported",
        "Données de démo": "Demo data",
        "Charger les données de démo": "Load demo data",
        "Réinitialiser la démo": "Reset demo",
        "La démo crée une classe fictive avec dix élèves, six exercices et un devoir actif. Pour essayer côté élève, saisissez le code de cette classe sur un iPad. La réinitialisation efface uniquement les données de démo.": "The demo creates a sample class with ten students, six exercises and an active assignment. To try the student side, enter this class's code on an iPad. Reset deletes demo data only.",
        "Ouvrir": "Open",
        "Par élève": "Per student",
        "Par exercice": "Per exercise",
        "Par classe": "Per class",

        // MARK: Period creation
        "Nouvelle séance": "New class period",
        "Détails de la séance": "Period details",
        "Nom (ex : Cours du 9 mai)": "Name (e.g. May 9 class)",
        "Début": "Start",
        "Fin": "End",
        "Sous-créneaux": "Sessions",
        "Ajouter un sous-créneau": "Add a session",
        "Une séance peut contenir plusieurs sous-créneaux ordonnés. Chaque sous-créneau a son propre mode de correction.": "A class period can have several ordered sessions, each with its own correction mode.",
        "Créer la séance": "Create period",
        "Nom du sous-créneau": "Session name",
        "Ordre libre": "Free order",
        "En attente de connexion": "Waiting for connection",
    ]
}
