"""Expected diagnosis of the wrong copies of the grading corpus: the skills
of the taxonomy acceptable for the first wrong step (the one that shows
the gap). Used by diagnosis_benchmark.py (real Claude) and checked
against the taxonomy by test_diagnosis_corpus.py.
"""

from grading_corpus import Case, _c

# Extra copies aimed at the diagnosis (not in the grading corpus).
EXTRA_CASES = [
    _c("pythagore-carres-doubles", "9e-10e",
       "Un triangle rectangle a des côtés de l'angle droit de 6 cm et 8 cm. Calculer l'hypoténuse.",
       r"10 \text{ cm}", [r"6^2 + 8^2 = 28", r"\sqrt{28} \approx 5,3 \text{ cm}"], False, 0),
    _c("trois-facteurs-oubli", "11e", r"Développer et réduire $(x+1)(x-2)(x+3)$", "x^3 + 2x^2 - 5x - 6",
       ["(x+1)(x-2) = x^2 - x - 2", "(x^2 - x - 2)(x+3) = x^3 + 3x^2 - x - 2"], False, 1),
    _c("facteur-negatif-signe", "9e-10e", r"Développer $-3(x - 2)$", "-3x + 6",
       ["-3(x - 2) = -3x - 6"], False, 0),
    _c("transposer-signe", "9e-10e", r"Résoudre $3x - 7 = 11$", "x = 6",
       ["3x = 11 - 7", "3x = 4", r"x = \frac{4}{3}"], False, 0),
]

# id → acceptable skill IDs for the first wrong step.
EXPECTED = {
    "priorites-faux": {"nombres.priorites.sans-parentheses"},
    "soustraction-faux": {"nombres.entiers-decimaux.addition-soustraction"},
    "oeufs-faux": {"problemes.modeliser.choisir-l-operation", "nombres.entiers-decimaux.multiplication"},
    "billes-faux": {"nombres.entiers-decimaux.multiplication"},
    "billes-phrase-fausse": {"problemes.repondre.phrase-reponse", "problemes.modeliser.etapes-intermediaires",
                             "problemes.repondre.verifier-la-vraisemblance"},
    "fractions-faux": {"nombres.fractions.additionner-denominateurs-differents"},
    "simplifier-incomplet": {"nombres.fractions.simplifier", "problemes.repondre.forme-demandee"},
    "pourcentage-faux": {"nombres.proportionnalite.pourcentage-d-une-quantite", "nombres.proportionnalite.evolutions"},
    "relatifs-faux": {"nombres.relatifs.regle-des-signes"},
    "carre-negatif-faux": {"nombres.relatifs.carre-d-un-negatif"},
    "puissances-faux": {"nombres.puissances.produit-meme-base"},
    "racine-faux": {"nombres.puissances.simplifier-racines"},
    "scientifique-forme": {"nombres.puissances.notation-scientifique"},
    "scientifique-faux": {"nombres.puissances.notation-scientifique", "nombres.puissances.exposant-negatif-nul"},
    "developper-faux": {"litteral.developper.simple-distributivite"},
    "identite-faux": {"litteral.developper.identites-remarquables"},
    "factoriser-non-fait": {"litteral.factoriser.identites-remarquables", "problemes.repondre.forme-demandee"},
    "factoriser-faux": {"litteral.factoriser.identites-remarquables"},
    "reduire-faux": {"litteral.reduire.termes-semblables", "litteral.reduire.avec-signes"},
    "eq1-faux": {"litteral.developper.simple-distributivite", "equations.premier-degre.avec-parentheses"},
    "eq1-signe-faux": {"equations.premier-degre.transposer", "equations.premier-degre.inconnue-des-deux-cotes",
                       "nombres.relatifs.additionner"},
    "eq1-parentheses-faux": {"nombres.relatifs.soustraire-une-expression", "equations.premier-degre.avec-parentheses",
                             "litteral.developper.facteur-negatif"},
    "eq-reponse-fraction-faux": {"equations.premier-degre.solution-fractionnaire", "equations.premier-degre.deux-etapes",
                                 "equations.premier-degre.une-etape", "nombres.entiers-decimaux.division"},
    "eq2-incomplet": {"equations.second-degre.x2-egal-a", "equations.second-degre.toutes-les-solutions"},
    "inequation-sens-faux": {"equations.inequations.changer-de-sens"},
    "systeme-une-inconnue": {"equations.systemes.substitution", "equations.systemes.combinaison",
                             "equations.systemes.interpreter"},
    "systeme-faux": {"equations.systemes.substitution", "equations.systemes.combinaison"},
    "pythagore-faux": {"geometrie.pythagore.hypotenuse"},
    "disque-perimetre": {"geometrie.aires-perimetres.disque"},
    "prix-faux": {"nombres.proportionnalite.quatrieme-proportionnelle", "problemes.modeliser.choisir-l-operation",
                  "nombres.proportionnalite.reconnaitre",
                  "nombres.entiers-decimaux.multiplication"},
    "conversion-faux": {"grandeurs.conversions.longueurs-masses"},
    "image-faux": {"fonctions.notion.image", "litteral.expressions.substituer", "nombres.puissances.definition"},
    "derivee-faux": {"fonctions.derivation.derivees-usuelles", "fonctions.derivation.somme-produit-par-constante"},
    "derivee-produit-faux": {"fonctions.derivation.produit"},
    "integrale-faux": {"analyse.integration.primitives-usuelles", "analyse.integration.calculer-integrale"},
    "limite-faux": {"analyse.limites.forme-indeterminee"},
    "exp-faux": {"equations.transcendantes.exponentielle", "equations.transcendantes.logarithme", "fonctions.exp-ln.proprietes-ln"},
    "trigo-faux": {"fonctions.trigonometrie.formules"},
    "proba-faux": {"probabilites.probabilites-base.equiprobabilite"},
    "moyenne-faux": {"probabilites.statistiques.moyenne"},
    "integrale-lineaire-borne-faux": {"analyse.integration.bornes", "analyse.integration.calculer-integrale"},
    "integrale-trigo-signe-faux": {"analyse.integration.primitives-usuelles"},
    "integrale-exp-faux": {"analyse.integration.primitives-usuelles"},
    "primitive-faux": {"analyse.integration.primitives-usuelles"},
    "ipp-faux": {"analyse.integration.par-parties"},
    "derivee-sin-oubli-faux": {"fonctions.derivation.composee", "fonctions.derivation.exp-ln-trigo"},
    "derivee-ln-faux": {"fonctions.derivation.composee", "fonctions.derivation.exp-ln-trigo"},
    "derivee-quotient-faux": {"fonctions.derivation.quotient"},
    "limite-infini-faux": {"analyse.limites.a-l-infini"},
    "ln-equation-faux": {"equations.transcendantes.logarithme", "fonctions.exp-ln.proprietes-ln"},
    "ln-proprietes-faux": {"fonctions.exp-ln.proprietes-ln"},
    "second-degre-delta-faux": {"equations.second-degre.discriminant"},
    "trigo-valeur-faux": {"fonctions.trigonometrie.valeurs-remarquables"},
    "trigo-equation-incomplet": {"equations.transcendantes.trigonometrique", "fonctions.trigonometrie.cercle-trigonometrique"},
    "trigo-duplication-faux": {"fonctions.trigonometrie.formules"},
    "trigo-triangle-cos-faux": {"geometrie.trigonometrie-triangle.choisir-le-rapport"},
    "proba-complement-faux": {"probabilites.probabilites-base.evenement-contraire"},
    "proba-conditionnelle-faux": {"probabilites.conditionnelles.formule"},
    "proba-deux-tirages-remise-faux": {"probabilites.probabilites-base.tirages"},
    "binomiale-oubli-coef-faux": {"probabilites.variables-aleatoires.binomiale", "probabilites.denombrement.combinaisons"},
    "esperance-faux": {"probabilites.variables-aleatoires.esperance-variance"},
    "combinaisons-arrangement-faux": {"probabilites.denombrement.combinaisons"},
    "mediane-faux": {"probabilites.statistiques.mediane-quartiles"},
    "suite-arithmetique-faux": {"analyse.suites.arithmetique", "analyse.suites.terme-general"},
    "suite-geometrique-faux": {"analyse.suites.geometrique", "analyse.suites.terme-general"},
    "somme-geometrique-faux": {"analyse.suites.sommes"},
    "complexe-produit-faux": {"complexes.algebrique.operations"},
    "complexe-module-faux": {"complexes.trigonometrique.module"},
    "produit-scalaire-faux": {"geometrie.vecteurs.produit-scalaire", "nombres.relatifs.additionner",
                              "nombres.relatifs.regle-des-signes"},
    # Extra cases
    "pythagore-carres-doubles": {"nombres.puissances.definition", "geometrie.pythagore.hypotenuse"},
    "trois-facteurs-oubli": {"litteral.developper.trois-facteurs"},
    "facteur-negatif-signe": {"litteral.developper.facteur-negatif"},
    "transposer-signe": {"equations.premier-degre.transposer"},
}
